# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xjMY4ZQ6rJoCzfCDaiaVau7hufpannXQ
"""

import cvxpy
cost = [0.18,0.23,0.05]
vit = [107,500,0]
cal = [72,121,65]
m=3
n=1
V= cvxpy.Variable((m,n))
objective = cvxpy.Minimize(cost@V)
constraints = [2000<=(cal@V) , (cal@V)<=2250 , 5000<=(vit@V) ,(vit@V)<=50000 , V<=10 , V>=0]
P = cvxpy.Problem(objective, constraints)
P.solve()
print("Optimized Servings:",V.value)
print("Optimized Value:",P.value)